"""seo_metrics competitors

Revision ID: 49d12957dd6d
Revises: efb39716d2de
Create Date: 2026-08-26 00:55:43.493073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d12957dd6d'
down_revision: Union[str, Sequence[str], None] = 'efb39716d2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_data', sa.Column('seo_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_data', 'seo_metrics')
    # ### end Alembic commands ###
