"""add raw_text to competitor_data

Revision ID: c46fb617d772
Revises: 60bd835f3559
Create Date: 2026-08-14 19:36:31.767839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46fb617d772'
down_revision: Union[str, Sequence[str], None] = '60bd835f3559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_data', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_data', 'raw_text')
    # ### end Alembic commands ###
